"""empty message

Revision ID: 8e5e5807b4c1
Revises: 
Create Date: 2018-04-30 11:16:06.968335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e5e5807b4c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=True),
                    sa.Column('description', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=True),
                    sa.Column('description', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('email', sa.String(length=60), nullable=True))
    op.add_column('employees', sa.Column('first_name', sa.String(length=60), nullable=True))
    op.add_column('employees', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('last_name', sa.String(length=60), nullable=True))
    op.add_column('employees', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('employees', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('username', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'])
    op.drop_column('employees', 'ID')
    op.drop_column('employees', 'SALARY')
    op.drop_column('employees', 'NAME')
    op.drop_column('employees', 'DESIGNATION')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('DESIGNATION', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('employees', sa.Column('NAME', mysql.VARCHAR(length=300), nullable=True))
    op.add_column('employees', sa.Column('SALARY', mysql.FLOAT(), nullable=True))
    op.add_column('employees', sa.Column('ID', mysql.INTEGER(display_width=255), nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_column('employees', 'username')
    op.drop_column('employees', 'role_id')
    op.drop_column('employees', 'password_hash')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'is_admin')
    op.drop_column('employees', 'id')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'department_id')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
