"""empty message

Revision ID: aca597ae101c
Revises: 
Create Date: 2018-04-30 16:59:53.232924

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aca597ae101c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('last_name', sa.String(length=60), nullable=True))
    op.add_column('employees', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('employees', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('username', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_column('employees', 'username')
    op.drop_column('employees', 'role_id')
    op.drop_column('employees', 'password_hash')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'is_admin')
    op.drop_column('employees', 'id')
    # ### end Alembic commands ###
