"""empty message

Revision ID: af63a38f475f
Revises: aca597ae101c
Create Date: 2018-05-02 01:52:02.495852

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'af63a38f475f'
down_revision = 'aca597ae101c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id', 'employees', ['id'], unique=True)
    # ### end Alembic commands ###
